### Variables
@baseUrl = http://localhost:3000
@contentType= application/json 


### Get the base url
GET {{baseUrl}}

### Get the tasks
GET {{baseUrl}}/tasks

### Get a task by ID
GET {{baseUrl}}/tasks/{{taskId}}

### Create a new task
# @name createTask
POST {{baseUrl}}/tasks
Content-Type: {{contentType}}

{
  "title": "New Task nuovo",
  "description": "This is a new task created via API con id dynamic",
  "status": "DONE"
}

### Set the task id
@taskId = {{ createTask.response.body.id }}

### Update task status
PATCH  {{baseUrl}}/tasks/{{taskId}}/status
Content-Type: {{contentType}}

{
  "status": "DONE"
}
### Update task 
PATCH  {{baseUrl}}/tasks/{{taskId}}
Content-Type: {{contentType}}

{
   "title": "New Task Modified",
  "description": "This is a new task descriotuib (modified)",
  "status": "OPEN"
}

### Delete task by ud
DELETE {{baseUrl}}/tasks/{{taskId}}

