### Variables
@baseUrl = http://localhost:3000
@contentType= application/json 


### Get the base url
GET {{baseUrl}}

### Get all the tasks
# @name getAllTasks
GET {{baseUrl}}/tasks

### Get all the tasks in status progress
# @name getAllInProgress
GET {{baseUrl}}/tasks?status=IN_PROGRESS
### Get all the tasks with search query
# @name getAllWithSearch
GET {{baseUrl}}/tasks?search=labels

### Get a task by ID
GET {{baseUrl}}/tasks/dfac58ff-b297-4641-ae23-b3f262182572

### Create a new task
# @name createTask
POST {{baseUrl}}/tasks
Content-Type: {{contentType}}

{
  "title": "New Task with this is new 12",
  "description": "This is a new task created via API con id dynamic e labels",
  "status": "OPEN",
  "userId": "eefdcb42-a2d6-4506-959d-a52698cbed19",
  "labels": [
    {
    "name": "medium"
    }
  ]
}

### Set the task id
@taskId = {{ createTask.response.body.id }}

### Update task status
PATCH  {{baseUrl}}/tasks/{{taskId}}/status
Content-Type: {{contentType}}

{
  "status": "DONE",
  "labels": []
}
### Update task 
PATCH  {{baseUrl}}/tasks/{{taskId}}
Content-Type: {{contentType}}

{
  "title": "New Task Modified",
  "description": "This is a new task descriotuib (modified)",
  "status": "OPEN"
}

### Delete task by ud
DELETE {{baseUrl}}/tasks/f6bece4b-d23c-4f19-b0b8-891921cf02b5

### Add labels to a task
# @name addLabels
POST {{baseUrl}}/tasks/8bbe3948-77d2-4521-91b6-6ee08becde8f/labels
Content-Type: {{contentType}}

[
  {
    "name": "new label 4"
  },
  {
    "name": "new label 5"
  }
]

### Remove labels to a task
# @name removeLabels
DELETE {{baseUrl}}/tasks/8bbe3948-77d2-4521-91b6-6ee08becde8f/labels
Content-Type: {{contentType}}

[ "new label 4", "new label 5"]

// docker compose up