### Variables
@baseUrl = http://localhost:3000
@contentType= application/json 


### Get the tasks
GET {{baseUrl}}/tasks

### Get a task by ID
GET {{baseUrl}}/tasks/11cae179-7eca-42ee-a546-702e83a28d32

### Create a new task
POST {{baseUrl}}/tasks
Content-Type: {{contentType}}

{
  "title": "New Task",
  "description": "This is a new task created via API",
  "status": "OPEN"
}

### Update task status
Patch {{baseUrl}}/tasks/11cae179-7eca-42ee-a546-702e83a28d32/status
Content-Type: {{contentType}}

{
  "status": "OPEN"
}